-- Run once in the Supabase SQL editor to add multi-tenant support.

create table users (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  telegram_chat_id text not null,
  webhook_secret text not null unique,
  created_at timestamptz not null default now()
);

alter table trades add column user_id uuid references users(id);

-- Backfill: insert a row for the existing owner using the current
-- TELEGRAM_CHAT_ID / WEBHOOK_SECRET env values, then set user_id on
-- existing trades to that row's id, e.g.:
--
-- insert into users (name, telegram_chat_id, webhook_secret)
-- values ('owner', '<TELEGRAM_CHAT_ID>', '<WEBHOOK_SECRET>')
-- returning id;
--
-- update trades set user_id = '<id from above>' where user_id is null;

-- Run once to move `trades` from "one row per event" to "one row per
-- position, updated on close" so a trade's open+close+TP/SL can be shown
-- together (needed for the frontend's trade-history table).
alter table trades add column position_id bigint;
alter table trades add column close_price numeric;
alter table trades add column tp numeric;
alter table trades add column sl numeric;
alter table trades add column status text default 'open';
alter table trades add column closed_at timestamptz;

-- Run once to support the "ตั้งค่าบัญชี" profile page — fields the user
-- edits themselves via the frontend, separate from `name` (the internal
-- label set by the owner in scripts/add-user.js).
alter table users add column first_name text;
alter table users add column last_name text;
alter table users add column email text;
alter table users add column mt5_account_id text;
alter table users add column mt5_server text;
alter table users add constraint users_email_unique unique (email);

-- Run once to support website login: POST /api/login checks email+password.
-- Passwords are set by an administrator on the account-management page
-- (there is no public sign-up or password-setup endpoint).
alter table users add column password_hash text;

-- Run once: mt5_account_id/mt5_server ended up unused (informational only,
-- never read by any backend logic) — dropped rather than left dead.
alter table users drop column mt5_account_id;
alter table users drop column mt5_server;

-- Run once to add server-enforced account roles and account suspension.
alter table users add column if not exists role text not null default 'user';
alter table users add column if not exists is_active boolean not null default true;
alter table users alter column telegram_chat_id drop not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'users_role_check'
      and conrelid = 'public.users'::regclass
  ) then
    alter table users add constraint users_role_check check (role in ('user', 'admin'));
  end if;
end $$;

-- Promote the first administrator manually after confirming that the account exists:
-- update users set role = 'admin' where lower(email) = lower('your-admin-email@example.com');
-- select id, email, role, is_active from users where lower(email) = lower('your-admin-email@example.com');

-- Emails are unique ignoring case: the original `unique (email)` constraint
-- is case-sensitive, so "A@x.com" and "a@x.com" could both exist and break
-- login lookup. Check for existing clashes first (must return no rows):
--   select lower(email), count(*) from users
--   where email is not null group by 1 having count(*) > 1;
create unique index if not exists users_email_lower_key on users (lower(email));

-- Per-user notification preferences (src/notification-settings.js).
-- Columns mirror the table currently in Supabase.
create table if not exists notification_settings (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references users(id),
  enabled boolean not null default true,
  notify_buy boolean not null default true,
  notify_sell boolean not null default true,
  notify_tp boolean not null default true,
  notify_sl boolean not null default true,
  notify_close boolean not null default true,
  notify_risk boolean not null default true,
  notify_daily_summary boolean not null default true,
  notify_weekly_summary boolean not null default false,
  min_pnl numeric,
  max_drawdown numeric,
  symbols text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Deleting an account must remove its trades + settings + the user row
-- atomically (the admin page's delete button calls this via supabase.rpc).
-- A plpgsql function runs as one transaction, so a failure rolls everything back.
-- Only the server (service_role) may call it.
create or replace function delete_user_cascade(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from trades                where user_id = p_user_id;
  delete from notification_settings where user_id = p_user_id;
  delete from users                 where id      = p_user_id;
  if not found then
    raise exception 'user % not found', p_user_id;
  end if;
end $$;

revoke all on function delete_user_cascade(uuid) from public, anon, authenticated;
grant execute on function delete_user_cascade(uuid) to service_role;

-- Row Level Security: enabled with NO policies, so the public anon key can
-- read/write nothing. The Node server uses the service_role key
-- (SUPABASE_SERVICE_KEY), which bypasses RLS. The browser never talks to
-- Supabase directly — it only calls the Node API.
alter table users                 enable row level security;
alter table trades                enable row level security;
alter table notification_settings enable row level security;

