-- schema.sql — โครงสร้างฐานข้อมูล (Supabase / PostgreSQL) ของทั้งระบบ
-- มี 3 ตาราง: users (บัญชีผู้ใช้) • trades (เทรดแต่ละออเดอร์) • notification_settings
-- (การตั้งค่าแจ้งเตือนรายคน)
-- พร้อมฟังก์ชัน delete_user_cascade (ลบบัญชีแบบปลอดภัย) และการเปิด RLS
-- (กันการเข้าถึงข้อมูลโดยตรง)
-- วิธีใช้: รันทั้งไฟล์ตั้งแต่บนลงล่างใน SQL Editor ของโปรเจกต์ที่ว่าง —
-- ไฟล์เรียงตามประวัติการแก้ไขโครงสร้างของระบบ
-- Run in the Supabase SQL editor, top to bottom, on an EMPTY project to build
-- the whole schema. The file reads as the migration history: the original
-- `trades` table first, then every change made to it afterwards.

-- The original table: one row per MT5 event, later extended below to one row
-- per position (position_id, close_price, tp, sl, status, closed_at) and tied
-- to a user (user_id).
-- [ตาราง trades] เก็บเทรด 1 ออเดอร์ต่อ 1 แถว: action (buy/sell), symbol, price, pnl
-- (กำไร/ขาดทุน), lot, timestamp (เวลาที่บันทึก)
-- คอลัมน์ position_id, close_price, tp, sl, status, closed_at, user_id
-- จะถูกเพิ่มภายหลังด้านล่าง
create table if not exists trades (
  id bigint generated by default as identity primary key,
  action text not null,
  symbol text not null,
  price numeric,
  pnl numeric,
  lot numeric,
  timestamp timestamptz default now()
);

-- Run once to add multi-tenant support.

-- [ตาราง users] บัญชีผู้ใช้: id, name, telegram_chat_id และ webhook_secret (รหัสที่ EA
-- ใช้บอกว่าข้อมูลเป็นของใคร ห้ามซ้ำ)
-- คอลัมน์อีเมล รหัสผ่าน role ฯลฯ จะถูกเพิ่มภายหลังด้านล่าง
create table users (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  telegram_chat_id text not null,
  webhook_secret text not null unique,
  created_at timestamptz not null default now()
);

-- ผูกทุกเทรดเข้ากับเจ้าของ (user_id → users.id)
-- ทำให้ผู้ใช้หลายคนใช้ระบบเดียวกันโดยข้อมูลไม่ปนกัน (multi-tenant)
alter table trades add column user_id uuid references users(id);

-- Backfill: insert a row for the existing owner using the current
-- TELEGRAM_CHAT_ID / WEBHOOK_SECRET env values, then set user_id on
-- existing trades to that row's id, e.g.:
--
-- insert into users (name, telegram_chat_id, webhook_secret)
-- values ('owner', '<TELEGRAM_CHAT_ID>', '<WEBHOOK_SECRET>')
-- returning id;
--
-- update trades set user_id = '<id from above>' where user_id is null;

-- Run once to move `trades` from "one row per event" to "one row per
-- position, updated on close" so a trade's open+close+TP/SL can be shown
-- together (needed for the frontend's trade-history table).
-- [สรุป] เพิ่ม position_id (เลขออเดอร์ของ MT5) เปลี่ยนจาก "1 แถวต่อ 1 เหตุการณ์" เป็น "1 แถวต่อ
-- 1 ออเดอร์":
-- ตอนเปิดเพิ่มแถว status = open, ตอนปิดอัปเดตแถวเดิม (close_price, pnl, status = closed,
-- closed_at)
alter table trades add column position_id bigint;
alter table trades add column close_price numeric;
alter table trades add column tp numeric;
alter table trades add column sl numeric;
alter table trades add column status text default 'open';
alter table trades add column closed_at timestamptz;

-- Run once to support the "ตั้งค่าบัญชี" profile page — fields the user
-- edits themselves via the frontend, separate from `name` (the internal
-- label set by the owner in scripts/add-user.js).
-- ชื่อ นามสกุล อีเมล ที่ผู้ใช้แก้เองได้ในหน้าโปรไฟล์ — อีเมลห้ามซ้ำ (unique)
alter table users add column first_name text;
alter table users add column last_name text;
alter table users add column email text;
alter table users add column mt5_account_id text;
alter table users add column mt5_server text;
alter table users add constraint users_email_unique unique (email);

-- Run once to support website login: POST /api/login checks email+password.
-- Passwords are set by an administrator on the account-management page
-- (there is no public sign-up or password-setup endpoint).
-- password_hash = รหัสผ่านที่เข้ารหัสด้วย bcrypt (ฐานข้อมูลไม่เก็บรหัสจริง) ใช้ตรวจตอน login
alter table users add column password_hash text;

-- Run once: mt5_account_id/mt5_server ended up unused (informational only,
-- never read by any backend logic) — dropped rather than left dead.
alter table users drop column mt5_account_id;
alter table users drop column mt5_server;

-- Run once to add server-enforced account roles and account suspension.
-- role = "user" หรือ "admin" และ is_active = บัญชีเปิดใช้งานอยู่ไหม (false = ถูกระงับ) —
-- ใช้ควบคุมสิทธิ์ที่เซิร์ฟเวอร์
-- ส่วน telegram_chat_id เปลี่ยนให้ว่างได้ เพราะ admin อาจสร้างบัญชีก่อนแล้วค่อยตั้ง Chat ID
-- ทีหลัง
alter table users add column if not exists role text not null default 'user';
alter table users add column if not exists is_active boolean not null default true;
alter table users alter column telegram_chat_id drop not null;

-- บังคับว่าคอลัมน์ role ต้องเป็น "user" หรือ "admin" เท่านั้น (เช็กก่อนว่ายังไม่มีเงื่อนไขนี้
-- เพื่อให้รันซ้ำได้โดยไม่ error)
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'users_role_check'
      and conrelid = 'public.users'::regclass
  ) then
    alter table users add constraint users_role_check check (role in ('user', 'admin'));
  end if;
end $$;

-- Promote the first administrator manually after confirming that the account exists:
-- update users set role = 'admin' where lower(email) = lower('your-admin-email@example.com');
-- select id, email, role, is_active from users where lower(email) = lower('your-admin-email@example.com');

-- Emails are unique ignoring case: the original `unique (email)` constraint
-- is case-sensitive, so "A@x.com" and "a@x.com" could both exist and break
-- login lookup. Check for existing clashes first (must return no rows):
--   select lower(email), count(*) from users
--   where email is not null group by 1 having count(*) > 1;
-- ทำให้อีเมลไม่ซ้ำ "โดยไม่สนตัวพิมพ์เล็กใหญ่" ด้วย unique index บน lower(email)
create unique index if not exists users_email_lower_key on users (lower(email));

-- Per-user notification preferences (src/notification-settings.js).
-- Columns mirror the table currently in Supabase.
-- [ตาราง notification_settings] การตั้งค่าแจ้งเตือนของผู้ใช้แต่ละคน (1 แถวต่อ 1 คน เพราะ
-- user_id ห้ามซ้ำ)
-- มีสวิตช์เปิด/ปิดแต่ละแบบ กำไรขั้นต่ำ เกณฑ์ Drawdown และรายชื่อคู่เงินที่เลือก
create table if not exists notification_settings (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references users(id),
  enabled boolean not null default true,
  notify_buy boolean not null default true,
  notify_sell boolean not null default true,
  notify_tp boolean not null default true,
  notify_sl boolean not null default true,
  notify_close boolean not null default true,
  notify_risk boolean not null default true,
  notify_daily_summary boolean not null default true,
  notify_weekly_summary boolean not null default false,
  min_pnl numeric,
  max_drawdown numeric,
  symbols text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Deleting an account must remove its trades + settings + the user row
-- atomically (the admin page's delete button calls this via supabase.rpc).
-- A plpgsql function runs as one transaction, so a failure rolls everything back.
-- Only the server (service_role) may call it.
-- [ฟังก์ชัน] ลบบัญชีพร้อมเทรดและการตั้งค่าเป็น transaction เดียว (ลบครบทั้งหมดหรือไม่ลบเลย)
-- security definer = รันด้วยสิทธิ์เจ้าของฟังก์ชัน จึงต้องจำกัดผู้เรียกให้เหลือเฉพาะ
-- service_role ตามด้านล่าง
create or replace function delete_user_cascade(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from trades                where user_id = p_user_id;
  delete from notification_settings where user_id = p_user_id;
  delete from users                 where id      = p_user_id;
  if not found then
    raise exception 'user % not found', p_user_id;
  end if;
end $$;

-- ปิดสิทธิ์เรียกฟังก์ชันนี้จากทุกคน แล้วเปิดให้เฉพาะ service_role (คือเซิร์ฟเวอร์ของเรา)
revoke all on function delete_user_cascade(uuid) from public, anon, authenticated;
grant execute on function delete_user_cascade(uuid) to service_role;

-- Row Level Security: enabled with NO policies, so the public anon key can
-- read/write nothing. The Node server uses the service_role key
-- (SUPABASE_SERVICE_KEY), which bypasses RLS. The browser never talks to
-- Supabase directly — it only calls the Node API.
-- [สรุป] เปิด RLS ทุกตารางโดยไม่ตั้ง policy → anon key (ที่ใครก็ดูได้ในเว็บ)
-- อ่าน/เขียนอะไรไม่ได้เลย
-- เซิร์ฟเวอร์ใช้ service_role key ซึ่งข้าม RLS ได้ จึงเป็นทางเดียวที่เข้าถึงข้อมูลได้
alter table users                 enable row level security;
alter table trades                enable row level security;
alter table notification_settings enable row level security;

